name: The Manifesto Co
favicon: null
layout_spectrum: 0.6859970421064645
typography_spectrum: 0.5507891837041825
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7746591919567436
  lightness: 0.2389226567465812
  saturation: 0.9789359814021736
  rhythmicContrast: 0.13057971908710897
purpose: []
